version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bookmarkuser
      POSTGRES_PASSWORD: bookmarkpassword
      POSTGRES_DB: bookmarkdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookmark-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bookmarkuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - bookmark-network
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://bookmarkuser:bookmarkpassword@postgres:5432/bookmarkdb
      JWT_SECRET: jwt_super_secret
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - bookmark-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  bookmark-network:
    driver: bridge
